#!/bin/bash -e

echo "Build hook running"

export GOLANG_VERSION='1.18'

if [[ "$DOCKER_TAG" =~ ^1.*|^2.* ]]; then
  export GOLANG_VERSION=$DOCKER_TAG
fi

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg GOLANG_VERSION=$GOLANG_VERSION \
             -f $DOCKERFILE_PATH \
             -t $IMAGE_NAME .
